== Results from Interoperability Experiments

OGC CDB and GeoPackage are both standards increasingly used in M&S and GEOINT, but they both contain weaknesses and strengths when it comes to the combined needs of both industries. The combined technology of GeoPackage and OGC CDB is hoped to be a deterministic repository of easily read geospatial datasets suitable for storage, runtime access, and dissemination for live, virtual, constructive, gaming, and Mission Command (MC) systems. The use of CDB raised concerns in both industries because it utilizes Esri Shapefiles and Presagis OpenFlight, both of which are now open standards but were once proprietary. The primary issue is that Shapefiles leverage the dBase IV format to store feature attribution. To address the limitations of ESRI Shapefiles within CDB, potential designs were explored to integrate OGC GeoPackage with OGC CDB. GeoPackage technology was designed to ensure Mobile / Handheld devices could interoperate with systems within the larger Command Post and U.S. Army Enterprise. Current Geopackage adaptations can natively store 3D information, routing information, various types of data ‘tiles’, and other geographically related datasets.  An implementation of OGC GeoPackage within CDB aligns CDB vector data storage with the U.S. Army architecture.

Four approaches were testing in the Interoperability Experiment:

• Experiment 1: Conversion of Shapefiles in one or more CDB data stores into GeoPackages as required for Experiments 2, 3, and/or 4.
• Experiment 2: One-to-one conversion of a Shapefile into a GeoPackage.
• Experiment 3: Store each CDB Level of Detail (LOD) as a layer in GeoPackage.
• Experiment 4: Store each Geocell of Vector Data as a layer in GeoPackage.

Experiment 2 was further broken down into Options 1a – 1d. Each experiment offered its own set of potential advantages, disadvantages, and lessons learned. 

Utilizing Option 1c:

•	Fully flattened instance, class, and extended level attribute tables
•	There is a 4:1 to 7:1 reduction in the number of files.
•	Some duplication of data, resulting in larger files.
•	There is one layer per GeoPackage.
•	The Feature Class and Extended Attributes are populated for each feature.
•	Full “Off the Shelf” GeoPackage software compatibility.
•	Best Experiment 2 option in terms of file size and performance time.

Utilizing Option 1d:

•	Flatten CDB standard instance and class attribute – maximum GIS tools compatibility
•	“Off the Shelf” GeoPackage software compatibility for CDB standard attributes.
•	Table for extended attributes using Related Tables GeoPackage extension
•	This approach utilizes a standard normalized relational database design, utilizing foreign keys.
•	Some duplication of data, resulting in larger files.
•	There is one layer per GeoPackage.
•	The Feature Class and Extended Attributes are populated for each feature.

The final method selected for conversion of a Shapefile CDB to a GeoPackage CDB is a hybrid of Options 1c and 1d. Because “Off the Shelf” GeoPackage software will not be aware of the class and extended level attributes, we needed to “flatten” the class level attributes with the instance level attributes.  It was not possible to effectively flatten the extended level attributes at this time, and those will remain in a separate table with regular table relationships.  The decision was made not to use the Related Tables GeoPackage extension.

Several observations were made during the experiments.  The output created by the recommended method of conversion allows backward compatibility. However, the GeoPackage CDB results in larger size on disk, which could be problematic. The GeoPackage format (especially as outputted by GDAL) is very space inefficient
when it comes to encoding tiles with small quantities of data.  But it does reduce the total number of files on disk significantly and eliminates the occurrence of dBase files containing 0 KB.

For more details on the experiments and information above, please see the OGC CDB Vector Data in GeoPackage Interoperability Experiment Engineering Report.

== Guidance on the use of GeoPackages

An GeoPackage is an open, standards-based, platform-independent, portable, self-describing, compact format for transferring geospatial information. It is a platform-independent SQLite database file. The GeoPackage specification was developed by OGC.  This document describes the encoding of Vector Data in GeoPackage only.

Per Requirement 4 of the CDB Vector GeoPackage Extension, the position of all points is expressed using WGS-84 geographic coordinates (latitude, longitude, altitude), as explained in Volume 8: CDB Spatial Reference Systems Guidance.

As detailed in the following table of GeoPackage Geometry Codes(Table 30 of Appendix G of the OGC GeoPackage Specification), the following geometry types are supported in GeoPackage:

[options="header",]
|===
|*Code* |*Name*
|0 | GEOMETRY
|1 | POINT 
|2 | LINESTRING 
|3 | POLYGON
|4 | MULTIPOIPNT
|5 | MULTILINESTRING
|6 | MULTIPOLYGON
|7 | GEOMETRYCOLLECTION
|===

Per Requirement 2 of the CDB Vector GeoPackage Extension, while the GeoPackage model supports encoding of 8 different types that can be stored in the same GeoPackage, the CDB standard requires a maximum of 3 feature geometry types per tile.

== Sample Conversion Tools
Sample conversion tools may be found in the Cognitics GitHub repo located at https://github.com/Cognitics/cdb-shp-geopackage-convert.

*Warning: Use the sample conversion code at your own risk. It is intended to provide an example on how to convert Shapefiles to GeoPackage in a CDB, and is not an OGC tested application. Make sure you test on a backup copy of your CDB first.*

The sample converter is written in Python, and uses GDAL (version 2.2.3 or greater) with the Python bindings. Binaries of GDAL can be found at https://trac.osgeo.org/gdal/wiki/DownloadingGdalBinaries.

To use the sample converter tool, use the following Syntax:

    Usage: Convert.py <Input Root CDB Directory> <Output Directory for GeoPackage Files>

The converter starts by calling the function:

    generateMetaFiles.generateMetaFiles(cDBRoot)

This function scans the CDB to find a list of Shapefiles. It stores a list of all Shapefiles in a file called shapeindex.py. Another file named shapemeta.py is generated with a list of shapefiles and the extents of each file. 

The shapemeta.py file is not necessary for the conversion, but can be useful for analysis. That block of code can be removed for a faster conversion if it isn't needed.

Next, the index file is scanned, and each ShapeFile is processed through:

    copyFeaturesFromShapeToGeoPackage(shpFilename,outputGeoPackageFile)

If the shapefile passed through this function is a feature file, and not a feature class or extended attribute file, the appropriate feature class and extended attributes DBF file (based on Selector2 in the filename) is ready by calling readDBF. All records in each file are read and stored in a dictionary.

Next, GDAL is used to create the appropriate GeoPackage file and layers. Then GDAL is used to open the ShapeFile and iterate through each feature. To flatten the feature class records, as each feature is read, any matching feature class records (based on the CNAM attribute) are added to the feature record.

After copyFeaturesFromShapeToGeoPackage has completed, the extended attribute DBF file that matches the feature file is read. The appropriate layer is created in the GeoPackage. The name of that layer is identical to the filename of the extended attribute DBF file, without the .dbf extension. Each record in the extended attribute DBF file is read and added to the new layer in the GeoPackage. Each record from the DFB file is copied into the GeoPackage layer.

Note that no additional relationships or foreign keys are necessary. The feature attributes that are used to link the features to the Extended Attributes in the GeoPackage are the same as the attributes from the ShapeFile (CEAI,GEAI, and VEAI) and have been renamed to indicate either the Instance or Class level (see Figure 1 in the Flattening the Schema of the Normative document).

After each feature ShapeFile has been processed, the conversion is complete. Note that none of the associated ShapeFile or DBF files are removed from the CDB.
